FROM java:8 
ADD target/FarmingAssistanceMS.jar FarmingAssistanceMS.jar
EXPOSE 8081
ENTRYPOINT [ "java","-jar","FarmingAssistanceMS.jar" ]

# FROM java:8
# ADD HelloDocker.java HelloDocker.java
# RUN javac HelloDocker.java
# CMD java HelloDocker